version: "3.8"

networks:
  hoarder_backend:
    name: hoarder_backend
  gateway:
    external: true
    name: gateway

services:
  web:
    container_name: hoarder
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION}
    restart: unless-stopped
    volumes:
      - $INSTALL_DIR/data:/data
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OLLAMA_BASE_URL:  $OLLAMA_BASE_URL
      INFERENCE_TEXT_MODEL: $INFERENCE_TEXT_MODEL
      INFERENCE_IMAGE_MODEL: $INFERENCE_IMAGE_MODEL
      DATA_DIR: /data
    networks:
      - hoarder_backend
      - gateway

  chrome:
    container_name: chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder_backend

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - $INSTALL_DIR/meilisearch:/meili_data
    networks:
      - hoarder_backend
